// Test definitions. Do NOT edit this file!
#define CATCH_CONFIG_MAIN // defines main() automatically
#include "catch.hpp"
#include "main.hpp"

// tests for exercise 1
TEST_CASE("Test1 ", "[Test 1]")
{
	double score;
	string sname;
	int ret1;
	double ret2;

	score = 90.0;
	ret1 = printStudents(score);
	cout << "The total printed students " << ret1 << endl;
	sname = "Bill";
	ret2 = getAVG(sname);
	cout << "The average for " << sname << "\t" << ret2 << endl;

	REQUIRE(ret1 == 9);
	REQUIRE(ret2 == 97.5);
}
TEST_CASE("Test2 ", "[Test 2]")
{
	double score;
	string sname;
	int ret1;
	double ret2;

	score = 95.0;
	ret1 = printStudents(score);
	cout << "The total printed students " << ret1 << endl;
	sname = "Jason";
	ret2 = getAVG(sname);
	cout << "The average for " << sname << "\t" << ret2 << endl;

	REQUIRE(ret1 == 4);
	REQUIRE(ret2 == 95);
}